Repository wecode-bootcamp-korea/46-1st-Code200-frontend, pull requests merged in 2023-06, with the labels that each got.

#4 [46기 김민정]Feature/main-new
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Main/New.js
  src/components/Main/New.scss
  src/components/Main/NewList.js
  src/pages/Main/Main.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#3 [46기 김민정]Feature/main-weekly
  public/data/bean.json
  public/data/beverage.json
  public/data/food.json
  public/index.html
  src/components/Main/WeeklyBest.js
  src/components/Main/WeeklyBest.scss
  src/components/Main/tapList.js
  src/components/RedDot/RedDot.js
  src/components/RedDot/RedDot.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#7 [46기 김민정]Feature/signup
  public/images/wediya.png
  src/pages/Signup/Agreement.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/checkList.js
  src/pages/Signup/inputList.js
  src/pages/Signup/userInfoList.json
Labels: 멘토 리뷰 요청

#12 [46기 김민지 ] Feature/ ProductDetail
  public/data/productDetail.json
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/UiData/productDetailNote.js
  src/pages/UiData/productDetailUiData.js
Labels: 멘토 리뷰 요청

#8 [46기 김민지] 상단 메뉴 UI 구현
  public/data/bean.json
  public/data/beverage.json
  public/data/cartSample.json
  public/data/category.json
  public/data/food.json
  public/data/productDetail.json
  public/data/sample.json
  public/images/coffee-beans fabicon.png
  public/images/coffee.jpeg
  public/images/coffeebean1.jpeg
  public/images/coffeebean2.jpeg
  public/images/coffeebean3.jpeg
  public/images/coffeebean4.jpeg
  public/images/coffeebean5.jpeg
  public/images/coffeebean6.jpeg
  public/images/coffeebean7.jpeg
  public/images/coffeebean8.jpeg
  public/images/wediya.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Main/New.js
  src/components/Main/New.scss
  src/components/Main/NewList.js
  src/components/Main/Slide.js
  src/components/Main/Slide.scss
  src/components/Main/SlideButtonList.js
  src/components/Main/SlideList.js
  src/components/Main/TapList.js
  src/components/Main/WeeklyBest.js
  src/components/Main/WeeklyBest.scss
  src/components/MyPage/MyPage.js
  src/components/MyPage/MyPage.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Main/Main.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/Signup/Agreement.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/checkList.js
  src/pages/Signup/inputList.js
  src/pages/Signup/userInfoList.json
  src/pages/UiData/productDetailNote.js
  src/pages/UiData/productDetailUiData.js
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#17 [46기 손자현] 별점 컴포넌트
  src/components/StarRating/StarRating.js
  src/components/StarRating/StarRating.scss
  src/pages/Cart/Cart.js
Labels: 멘토 리뷰 요청

#11 [46기 손자현] 수량 조정 버튼 컴포넌트
  src/components/QuantityBtn/QuantityBtn.js
  src/components/QuantityBtn/QuantityBtn.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
Labels: 멘토 리뷰 요청

#21 [46기 김민정] Feature/review
  public/data/reviewSample.json
  public/images/star.png
  src/Router.js
  src/components/Main/New.js
  src/components/Main/New.scss
  src/components/Main/NewList.js
  src/components/Main/Slide.js
  src/components/Main/Slide.scss
  src/components/Main/SlideButtonList.js
  src/components/Main/SlideList.js
  src/components/Main/TapList.js
  src/components/Main/WeeklyBest.js
  src/components/Main/WeeklyBest.scss
  src/components/Review/Review.js
  src/components/Review/Review.scss
  src/components/StarRating/StarRating.js
  src/components/StarRating/StarRating.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#20 [46기 김민지] 주문/결제 페이지 구현
  src/pages/Order/Order.js
  src/pages/Order/Order.scss
  src/pages/Order/OrderAddress.js
  src/pages/Order/OrderAddress.scss
  src/pages/Order/OrderDisCount.js
  src/pages/Order/OrderDisCount.scss
  src/pages/Order/OrderInfo.js
  src/pages/Order/OrderInfo.scss
  src/pages/Order/OrderMethod.js
  src/pages/Order/OrderMethod.scss
  src/pages/Order/OrderPay.js
  src/pages/Order/OrderPay.scss
  src/pages/Order/OrderProduct.js
  src/pages/Order/OrderProduct.scss
  src/pages/Order/OrderUiData/card.js
  src/pages/Order/OrderUiData/delivery.js
  src/pages/Order/OrderUiData/message.js
  src/pages/Order/OrderUiData/payMethod.js
  src/pages/Order/OrderUiData/period.js
  src/pages/Order/OrderUiData/phone.js
  src/pages/Order/modalShowTop.scss
Labels: 멘토 리뷰 요청

#2 [46기 옥준우] Feature/Login
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/common.scss
Labels: 수정 요청

#18 [46기 김민정] feature/signup 기능구현
  public/images/logo.png
  src/pages/Signup/Agreement.js
  src/pages/Signup/GenderCheckList.js
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.scss
  src/pages/Signup/checkList.js
  src/pages/Signup/inputList.js
Labels: 멘토 리뷰 요청

#28 [46기 옥준우] Feature/login
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 멘토 리뷰 요청

#31 [46기 옥준우] feature/login
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#32 [46기 옥준우] feature/footer
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#33 [46기 옥준우] Feature/Login
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#34 [46기 손자현] 제품 리스트 페이지 구현
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/pages/Login/Login.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#26 [46기 김민정]Feature/main card
  public/images/down-arrow.png
  public/images/up-arrow.png
  src/components/Main/Data/NewList.js
  src/components/Main/Data/SlideButtonList.js
  src/components/Main/Data/SlideList.js
  src/components/Main/Data/TapList.js
  src/components/Main/New/New.js
  src/components/Main/New/New.scss
  src/components/Main/Slide/Slide.js
  src/components/Main/WeeklyBest/WeeklyBest.js
  src/components/Main/WeeklyBest/WeeklyBest.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/components/Scroll/Scroll.js
  src/components/Scroll/Scroll.scss
  src/pages/Main/Main.js
Labels: 완료

#36 [46기 김민정] feature/main-slide-function
  src/components/Main/Slide/Slide.js
  src/components/Main/Slide/Slide.scss
Labels: 완료

#35 [46기 옥준우] Feature/login
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#37 [46기 김민정]feature/myWediya
  public/images/next.png
  src/Router.js
  src/pages/myWediya/myPageList.js
  src/pages/myWediya/myWediya.js
  src/pages/myWediya/myWediya.scss
Labels: 멘토 리뷰 요청

#27 [46기 김민지] 주문/결제 mock data 생성 및 주문자정보 불러오기
  public/data/order.json
  src/pages/Order/Order.js
  src/pages/Order/OrderAddress.js
  src/pages/Order/OrderAddress.scss
  src/pages/Order/OrderDisCount.js
  src/pages/Order/OrderDisCount.scss
  src/pages/Order/OrderInfo.js
  src/pages/Order/OrderInfo.scss
  src/pages/Order/OrderMethod.js
  src/pages/Order/OrderMethod.scss
  src/pages/Order/OrderPay.js
  src/pages/Order/OrderProduct.js
  src/pages/Order/OrderProduct.scss
Labels: 멘토 리뷰 요청

#24 [46기 김민지] 상품상세 기능 구현
  public/data/productDetail.json
  src/Router.js
  src/components/Count/Count.js
  src/components/Count/Count.scss
  src/components/Like/Like.js
  src/components/Like/Like.scss
  src/components/Nav/Nav.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/UiData/productDetailBottomImg.js
  src/pages/UiData/productDetailNote.js
  src/pages/UiData/productDetailUiData.js
Labels: 멘토 리뷰 요청

#25 [46기 김민지 ] 카테고리 기능 추가
  public/data/category.json
  public/index.html
  src/components/MyPage/MyPage.js
  src/components/MyPage/MyPage.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/navShowTop.scss
Labels: 멘토 리뷰 요청

#44 [46기 김민지] nav 카테고리 조회 시 의존성 배열 추가
  src/components/Nav/Nav.js
Labels: 멘토 리뷰 요청

#43 [46기 김민지] 상품 상세페이지 세부기능 수정
  src/Router.js
  src/components/ProductCard/ProductCard.js
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#45 [46기 김민지 ] 기능 수정
  src/components/Nav/Nav.js
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청

#47 [46기 김민정]Feature/main modify
  .vscode/e
  src/components/Main/Slide/Slide.scss
  src/components/Main/WeeklyBest/WeeklyBest.js
  src/components/QuantityBtn/QuantityBtn.js
  src/components/Review/Review.scss
  src/pages/Signup/Signup.js
  src/pages/myWediya/myWediya.js
Labels: 멘토 리뷰 요청

#48 [46기 김민지] 세부기능 수정
  src/components/Main/WeeklyBest/WeeklyBest.js
  src/components/MyPage/MyPage.js
  src/components/Nav/Nav.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/ProductList.js
Labels: 멘토 리뷰 요청
